Update immortalwrt-x86_64.yml

diff --git a/.github/workflows/immortalwrt-x86_64.yml b/.github/workflows/immortalwrt-x86_64.yml
--- a/.github/workflows/immortalwrt-x86_64.yml
+++ b/.github/workflows/immortalwrt-x86_64.yml
@@ -86,6 +86,11 @@ jobs:
       - name: Update feeds
         run: cd immortalwrt && ./scripts/feeds update -a
 
+      - name: Symlink lua-neturl if present
+        run: |
+          cd immortalwrt
+          [ -d feeds/packages/lang/lua-neturl ] && ln -sfn feeds/packages/lang/lua-neturl feeds/small/lua-neturl || echo "⚠️ lua-neturl not found, skip linking"
+
       - name: Install feeds
         run: cd immortalwrt && ./scripts/feeds install -a
 
@@ -100,13 +105,6 @@ jobs:
           cd immortalwrt
           rm -rf feeds/packages/lang/golang
           git clone https://github.com/sbwml/packages_lang_golang -b 24.x feeds/packages/lang/golang
-
-      - name: Replace the same package of the small project with the immortalwrt project lua-neturl
-        run: |
-          cd immortalwrt
-          echo "用immortalwrt项目lua-neturl替换small项目的相同包以避免错误..."
-          rm -rf feeds/small/lua-neturl
-          ln -s feeds/packages/lang/lua-neturl feeds/small/lua-neturl
 
       - name: Load custom configuration
         run: |
